apiVersion: v1
kind: Secret
metadata:
  name: {{ template "sftp.fullname" . }}
  labels:
{{ include "sftp.labels" . | indent 4 }}
type: Opaque
stringData:
  sftp.json: |-
{{ .Values.configuration | toPrettyJson | nindent 4 }}
  