apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "sftp.fullname" . }}
  labels:
    {{- include "sftp.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "sftp.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "sftp.selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "sftp.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      {{- with .Values.initContainers }}
      initContainers:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          {{- if .Values.image.tag }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          {{- else }}
          image: "{{ .Values.image.repository }}:{{ .Chart.AppVersion }}"
          {{- end }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: ssh
              containerPort: 22
              protocol: TCP
          {{- if or .Values.configuration .Values.storage.volumeMounts }}
          volumeMounts:
          {{- if and .Values.persistence.enabled }}
          - name: data
              mountPath: "{{ .Values.persistence.mountPath }}"
              subPath: "{{ .Values.persistence.subPath }}"
          {{- end }}    
          {{- if .Values.configuration }}
            - name: sftp-json
              mountPath: "/app/config/sftp.json"
              subPath: sftp.json
              readOnly: true
          {{- end }}
          {{- with .Values.storage.volumeMounts }}
          {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- end }}    
          livenessProbe:
            tcpSocket:
              port: ssh
          readinessProbe:
            tcpSocket:
              port: ssh
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- if or .Values.configuration .Values.storage.volumes }}
      volumes:
      {{- if and .Values.persistence.enabled }}
      - name: data
        persistentVolumeClaim:
          claimName: {{ if .Values.persistence.existingClaim }}{{ .Values.persistence.existingClaim }}{{- else }}{{ template "sftp.fullname" . }}{{- end }}
      {{- else }}
      {{- if .Values.configuration }}
        - name: sftp-json
          secret:
            secretName: {{ include "sftp.fullname" . }}
            items:
              - key: sftp.json
                path: sftp.json
      {{- end }}
      {{- with .Values.storage.volumes }}
      {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
